name: CI

on:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1237
          bb: 1.3.191

      - name: Run clj-kondo lint
        run: clojure -M:clj-kondo --lint src

      - name: Lint for vars that are too large
        run: bb lint:large-vars

      - name: Lint for undocumented namespaces
        run: bb lint:ns-docstrings

      - name: Lint to minimize public vars
        run: bb lint:minimize-public-vars

      - name: Check outdated dependencies
        uses: liquidz/antq-action@main
        with:
          excludes: 'borkdude/carve clojure/brew-install'

