name: CI

on:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1165
          bb: 0.8.2

      - name: Run clj-kondo lint
        run: clojure -M:clj-kondo --lint src

      - name: Check outdated dependencies
        uses: liquidz/antq-action@main

      - name: Lint for vars that are too large
        run: bb lint:large-vars

      - name: Lint for undocumented namespaces
        run: bb lint:ns-docstrings
